### ISSUE TITLE
Add automatic release stage

### ISSUE THREAD

**Issue by jpwahle** [Multi-Agent-LLMs/mallm#68]
We could add a simple pipeline that automatically builds a release when we merge on main, pushes to different registries (pip, docker), and adds a versioned release to GitHub.

[Here](https://github.com/jpwahle/cs-insights-frontend/blob/078f2a4822ee4cf455a6e5362cde9560c03f0677/.github/workflows/release.yml) is an example from one of our other projects, the GH Action workflow is pretty straightforward.

**Comment by lkaesberg** [comment]
@jonas-becker I added the pipeline, but you added a package (distinct-n) which is installed via GitHub. This is not allowed for pypi. We either remove it or we find some alternative package for distinct-n.

**Comment by jonas-becker** [comment]
> @jonas-becker I added the pipeline, but you added a package (distinct-n) which is installed via GitHub. This is not allowed for pypi. We either remove it or we find some alternative package for distinct-n.

I addressed this in PR #143. (removed the metric)
